name       : bat
version    : 0.12.1
release    : 7
source     :
    - https://github.com/sharkdp/bat/archive/v0.12.1.tar.gz : 1dd184ddc9e5228ba94d19afc0b8b440bfc1819fef8133fe331e2c0ec9e3f8e2
license    :
    - Apache-2.0
    - MIT
component  : system.utils
summary    : bat supports syntax highlighting for a large number of programming and markup languages
description: |
    bat supports syntax highlighting for a large number of programming and markup languages
networking : yes
clang      : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/bat $installdir/usr/bin/bat
    install -Dm00644 doc/bat.1 $installdir/usr/share/man/man1/bat.1
check      : |
    cargo test
