name       : bat
version    : 0.15.4
release    : 13
source     :
    - https://github.com/sharkdp/bat/archive/v0.15.4.tar.gz : 03b7c8ad6221ca87cecd71f9e3e2167f04f750401e2d3dcc574183aabeb76a8b
license    :
    - Apache-2.0
    - MIT
component  : system.utils
summary    : bat supports syntax highlighting for a large number of programming and markup languages
description: |
    bat supports syntax highlighting for a large number of programming and markup languages
networking : yes
clang      : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/bat $installdir/usr/bin/bat
    find ./ -name bat.1 -exec install -Dm00644 {} $installdir/usr/share/man/man1/bat.1 \;
    find ./ -name bat.fish -exec install -Dm00644 {} $installdir/usr/share/fish/vendor_completions.d/bat.fish \;
check      : |
    cargo test
