name       : bat
version    : 0.9.0
release    : 3
source     :
    - https://github.com/sharkdp/bat/archive/v0.9.0.tar.gz : 4ce9c118cf5da1159a882dea389f3c5737b5d98192e9a619b0fe8c1730341cc6
license    :
    - Apache-2.0
    - MIT
component  : system.utils
summary    : bat supports syntax highlighting for a large number of programming and markup languages
description: |
    bat supports syntax highlighting for a large number of programming and markup languages
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/bat $installdir/usr/bin/bat
    install -Dm00644 doc/bat.1 $installdir/usr/share/man/man1/bat.1
    install -Dm00644 target/release/build/bat-*/out/bat.bash $installdir/usr/share/bash-completion/completions/bat
    install -Dm00644 target/release/build/bat-*/out/bat.fish $installdir/usr/share/fish/completions/bat.fish
    install -Dm00644 target/release/build/bat-*/out/_bat $installdir/usr/share/zsh/site-functions/_bat
check      : |
    cargo test
