name       : bat
version    : 0.12.0
release    : 6
source     :
    - https://github.com/sharkdp/bat/archive/v0.12.0.tar.gz : 7a3d0d94b6bffa00644a4afbc5952f87965f4723de3878b97ef8b7ebfd912477
license    :
    - Apache-2.0
    - MIT
component  : system.utils
summary    : bat supports syntax highlighting for a large number of programming and markup languages
description: |
    bat supports syntax highlighting for a large number of programming and markup languages
networking : yes
clang      : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/bat $installdir/usr/bin/bat
    install -Dm00644 doc/bat.1 $installdir/usr/share/man/man1/bat.1
    install -Dm00644 assets/completions/bat.fish $installdir/usr/share/fish/completions/bat.fish
check      : |
    cargo test
