name       : bat
version    : 0.11.0
release    : 5
source     :
    - https://github.com/sharkdp/bat/archive/v0.11.0.tar.gz : bb4e39efadfab71c0c929a92b82dac58deacfe2a4eb527d4256ac0634e042ed2
license    :
    - Apache-2.0
    - MIT
component  : system.utils
summary    : bat supports syntax highlighting for a large number of programming and markup languages
description: |
    bat supports syntax highlighting for a large number of programming and markup languages
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/bat $installdir/usr/bin/bat
    install -Dm00644 doc/bat.1 $installdir/usr/share/man/man1/bat.1
    install -Dm00644 assets/completions/bat.fish $installdir/usr/share/fish/completions/bat.fish
check      : |
    cargo test
