name       : bat
version    : 0.15.1
release    : 12
source     :
    - https://github.com/sharkdp/bat/archive/v0.15.1.tar.gz : 6f64899870bb16abd82a86c6a34c165f78603514e6ebb8ddf920b59095eba57d
license    :
    - Apache-2.0
    - MIT
component  : system.utils
summary    : bat supports syntax highlighting for a large number of programming and markup languages
description: |
    bat supports syntax highlighting for a large number of programming and markup languages
networking : yes
clang      : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/bat $installdir/usr/bin/bat
    find ./ -name bat.1 -exec install -Dm00644 {} $installdir/usr/share/man/man1/bat.1 \;
    find ./ -name bat.fish -exec install -Dm00644 {} $installdir/usr/share/fish/vendor_completions.d/bat.fish \;
check      : |
    cargo test
