name       : bat
version    : 0.18.2
release    : 21
source     :
    - https://github.com/sharkdp/bat/archive/refs/tags/v0.18.2.tar.gz : b176787e27da1f920b655bcd71b66c1569d241e2272bb9a4f6a64e6501c0cf2a
license    :
    - Apache-2.0
    - MIT
homepage   : https://github.com/sharkdp/bat
component  : system.utils
summary    : bat supports syntax highlighting for a large number of programming and markup languages
description: |
    bat supports syntax highlighting for a large number of programming and markup languages
networking : yes
clang      : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/bat $installdir/usr/bin/bat
    install -Dm00644 target/release/build/*/out/assets/manual/bat.1 $installdir/usr/share/man/man1/bat.1
    install -Dm00644 target/release/build/*/out/assets/completions/bat.fish $installdir/usr/share/fish/vendor_completions.d/bat.fish
    install -Dm00644 target/release/build/*/out/assets/completions/bat.zsh $installdir/usr/share/zsh/site-functions/_bat
    install -Dm00644 target/release/build/*/out/assets/completions/bat.bash $installdir/usr/share/bash-completion/completions/bat
check      : |
    cargo test
