name       : bat
version    : 0.19.3
release    : 23
source     :
    - https://github.com/sharkdp/bat/archive/refs/tags/v0.19.0.tar.gz : 6a920cad1e7ae069eb9393f5b6883e0a7f2c957186b1075976331daaa5e0468a
license    :
    - Apache-2.0
    - MIT
homepage   : https://github.com/sharkdp/bat
component  : system.utils
summary    : A cat(1) clone with syntax highlighting and Git integration.
description: |
    A cat(1) clone which supports syntax highlighting for a large number of programming and markup languages. bat communicates with git to show modifications with respect to the index. By default, bat pipes its own output to a pager (e.g less) if the output is too large for one screen. 
networking : yes
clang      : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/bat $installdir/usr/bin/bat
    install -Dm00644 target/release/build/*/out/assets/manual/bat.1 $installdir/usr/share/man/man1/bat.1
    install -Dm00644 target/release/build/*/out/assets/completions/bat.fish $installdir/usr/share/fish/vendor_completions.d/bat.fish
    install -Dm00644 target/release/build/*/out/assets/completions/bat.zsh $installdir/usr/share/zsh/site-functions/_bat
    install -Dm00644 target/release/build/*/out/assets/completions/bat.bash $installdir/usr/share/bash-completion/completions/bat
check      : |
    cargo test
