name       : bat
version    : 0.18.1
release    : 19
source     :
    - https://github.com/sharkdp/bat/archive/refs/tags/v0.18.1.tar.gz : ab5246c3bec8745c14ca9a0473971f00fbce2fdc1ce7842e0a96676ee5eac2af
license    :
    - Apache-2.0
    - MIT
homepage   : https://github.com/sharkdp/bat
component  : system.utils
summary    : bat supports syntax highlighting for a large number of programming and markup languages
description: |
    bat supports syntax highlighting for a large number of programming and markup languages
networking : yes
clang      : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/bat $installdir/usr/bin/bat
    find ./ -name bat.1 -exec install -Dm00644 {} $installdir/usr/share/man/man1/bat.1 \;
    find ./ -name bat.fish -exec install -Dm00644 {} $installdir/usr/share/fish/vendor_completions.d/bat.fish \;
    find ./ -name bat.zsh -exec install -Dm00644 {} $installdir/usr/share/zsh/site-functions/_bat \;
check      : |
    cargo test
