name       : bat
version    : 0.13.0
release    : 8
source     :
    - https://github.com/sharkdp/bat/archive/v0.13.0.tar.gz : f4aee370013e2a3bc84c405738ed0ab6e334d3a9f22c18031a7ea008cd5abd2a
license    :
    - Apache-2.0
    - MIT
component  : system.utils
summary    : bat supports syntax highlighting for a large number of programming and markup languages
description: |
    bat supports syntax highlighting for a large number of programming and markup languages
networking : yes
clang      : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/bat $installdir/usr/bin/bat
    find ./ -name bat.1 -exec install -Dm00644 {} $installdir/usr/share/man/man1/bat.1 \;
check      : |
    cargo test
