name       : bat
version    : 0.15.0
release    : 11
source     :
    - https://github.com/sharkdp/bat/archive/v0.15.0.tar.gz : 702b330d2938426679b3b0d50334b1518b4fb1d779220f2e32e68dfa1bb9fc0f
license    :
    - Apache-2.0
    - MIT
component  : system.utils
summary    : bat supports syntax highlighting for a large number of programming and markup languages
description: |
    bat supports syntax highlighting for a large number of programming and markup languages
networking : yes
clang      : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/bat $installdir/usr/bin/bat
    find ./ -name bat.1 -exec install -Dm00644 {} $installdir/usr/share/man/man1/bat.1 \;
    find ./ -name bat.fish -exec install -Dm00644 {} $installdir/usr/share/fish/vendor_completions.d/bat.fish \;
check      : |
    cargo test
