name       : bat
version    : 0.6.0
release    : 1
source     :
    - https://github.com/sharkdp/bat/archive/v0.6.0.tar.gz : 3e182844c861cad5e214e504a81930bccf3c3916ee6821a73e932540b1c2de46
license    : 
    - Apache-2.0
    - MIT
component  : system.utils
summary    : bat supports syntax highlighting for a large number of programming and markup languages
description: |
    bat supports syntax highlighting for a large number of programming and markup languages
networking : yes
builddeps  :
    - cargo
    - rust 
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/bat $installdir/usr/bin/bat
    install -Dm00664 doc/bat.1 $installdir/usr/share/man/man1/bat.1
